name: Node.js Package

on:
  [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@smith-ai'
      - run: envsubst < .npmrc > .npmrc
      - run: mv .npmrc /home/runner/work/_temp/.npmrc
      - run: npm cache clean --force
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
